---
- name: Remove Polkadot
  hosts: all
  vars:
    - user: polkadot

  tasks:
    - name: Stop service
      become: yes
      ignore_errors: yes
      systemd:
        name: polkadot
        state: stopped

    - name: Delete user
      become: yes
      user:
        name: '{{ user }}'
        state: absent
        remove: yes

    - name: Delete group
      become: yes
      group:
        name: '{{ user }}'
        state: absent

    - name: Delete SystemD config
      become: yes
      file:
        path: /etc/systemd/system/polkadot.service
        state: absent

    - name: Reload SystemD
      become: yes
      systemd:
        daemon_reload: yes

    - name: Delete Polkadot executable
      become: yes
      file:
        path: /usr/local/bin/polkadot
        state: absent
