---
- name: Remove Gear Collator
  hosts: all
  vars:
    nodes:
      - user: alice
      - user: bob
      - user: rpc1
      - user: charlie
      - user: dave
      - user: rpc2

  tasks:
    - name: Stop service
      become: yes
      loop: '{{ nodes }}'
      ignore_errors: yes
      systemd:
        name: gear-collator-{{ item.user }}
        state: stopped

    - name: Delete user
      become: yes
      loop: '{{ nodes }}'
      user:
        name: '{{ item.user }}'
        state: absent
        remove: yes

    - name: Delete group
      become: yes
      loop: '{{ nodes }}'
      group:
        name: '{{ item.user }}'
        state: absent

    - name: Delete SystemD config
      become: yes
      loop: '{{ nodes }}'
      file:
        path: /etc/systemd/system/gear-collator-{{ item.user }}.service
        state: absent

    - name: Reload SystemD
      become: yes
      systemd:
        daemon_reload: yes

    - name: Delete Gear collator executable
      become: yes
      file:
        path: /usr/local/bin/gear-collator
        state: absent
