---
- name: Install Rococo
  hosts: all
  vars:
    nodes:
      - name: alice # 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
        node_key: '0000000000000000000000000000000000000000000000000000000000000001'
        chain: bootnode
        debug: yes

      - name: bob # 12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD
        node_key: '0000000000000000000000000000000000000000000000000000000000000002'
        chain: default
        port_p2p: 30334
        port_ws: 9945

      - name: charlie # 12D3KooWSCufgHzV4fCwRijfH2k3abrpAJxTKxEvN1FDuRXA2U9x
        node_key: '0000000000000000000000000000000000000000000000000000000000000003'
        chain: default
        port_p2p: 30335
        port_ws: 9946

      - name: dave # 12D3KooWSsChzF81YDUKpe9Uk5AHV5oqAaXAcWNSPYgoLauUk4st
        node_key: '0000000000000000000000000000000000000000000000000000000000000004'
        chain: default
        port_p2p: 30343
        port_ws: 9947

      - name: eve # 12D3KooWSuTq6MG9gPt7qZqLFKkYrfxMewTZhj9nmRHJkPwzWDG2
        node_key: '0000000000000000000000000000000000000000000000000000000000000005'
        chain: default
        port_p2p: 30344
        port_ws: 9948

      - name: ferdie # 12D3KooWMz5U7fR8mF5DNhZSSyFN8c19kU63xYopzDSNCzoFigYk
        node_key: '0000000000000000000000000000000000000000000000000000000000000006'
        chain: default
        port_p2p: 30345
        port_ws: 9949

  tasks:
    - name: Create group
      become: yes
      loop: '{{ nodes }}'
      group:
        name: '{{ item.name }}'
        state: present

    - name: Create user
      become: yes
      loop: '{{ nodes }}'
      user:
        name: '{{ item.name }}'
        groups: '{{ item.name }}'
        shell: /sbin/nologin
        append: yes
        state: present

    - name: Copy spec JSON
      become: yes
      loop: '{{ nodes }}'
      copy:
        src: rococo-{{ item.chain }}-raw.json
        dest: /home/{{ item.name }}
        owner: '{{ item.name }}'
        group: '{{ item.name }}'

    - name: Copy SystemD config
      become: yes
      loop: '{{ nodes }}'
      template:
        src: rococo.service.j2
        dest: /etc/systemd/system/rococo-{{ item.name }}.service
        owner: root
        group: root

    - name: Stop service
      become: yes
      loop: '{{ nodes }}'
      systemd:
        name: rococo-{{ item.name }}
        state: stopped
        daemon_reload: yes

    - name: Download polkadot executable
      become: yes
      get_url:
        url: https://github.com/paritytech/polkadot/releases/download/v0.9.29/polkadot
        dest: /usr/local/bin
        mode: '0755'
        force: yes
        owner: root
        group: root

    - name: Start service
      become: yes
      loop: '{{ nodes }}'
      systemd:
        name: rococo-{{ item.name }}
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Stop logging
      become: yes
      register: rsyslog
      systemd:
        name: rsyslog
        state: stopped
        enabled: no

    - name: Reboot
      when: rsyslog is changed
      become: yes
      reboot:
