---
- name: Install Rococo
  hosts: all
  vars:
    nodes:
      - name: alice
        node_key: '0000000000000000000000000000000000000000000000000000000000000001'
      - name: bob
        port_p2p: '30334'
        port_ws: '9945'
        bootnode: '/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'

  tasks:
    - name: Create group
      become: yes
      loop: '{{ nodes }}'
      group:
        name: '{{ item.name }}'
        state: present

    - name: Create user
      become: yes
      loop: '{{ nodes }}'
      user:
        name: '{{ item.name }}'
        groups: '{{ item.name }}'
        shell: /sbin/nologin
        append: yes
        state: present

    - name: Copy spec JSON
      become: yes
      loop: '{{ nodes }}'
      copy:
        src: rococo-custom-2-raw.json
        dest: /home/{{ item.name }}
        owner: '{{ item.name }}'
        group: '{{ item.name }}'

    - name: Copy SystemD config
      become: yes
      loop: '{{ nodes }}'
      template:
        src: rococo.service.j2
        dest: /etc/systemd/system/rococo-{{ item.name }}.service
        owner: root
        group: root

    - name: Stop service
      become: yes
      loop: '{{ nodes }}'
      systemd:
        name: rococo-{{ item.name }}
        state: stopped
        daemon_reload: yes

    - name: Download polkadot executable
      become: yes
      get_url:
        url: https://github.com/paritytech/polkadot/releases/download/v0.9.26/polkadot
        dest: /usr/local/bin
        mode: 0755
        force: yes
        owner: root
        group: root

    - name: Start service
      become: yes
      loop: '{{ nodes }}'
      systemd:
        name: rococo-{{ item.name }}
        state: started
        enabled: yes
        daemon_reload: yes
