---
- name: Remove Rococo
  hosts: all
  vars:
    nodes:
      - name: alice
      - name: bob
      - name: charlie

  tasks:
    - name: Stop service
      become: yes
      loop: '{{ nodes }}'
      ignore_errors: yes
      systemd:
        name: rococo-{{ item.name }}
        state: stopped

    - name: Delete user
      become: yes
      loop: '{{ nodes }}'
      user:
        name: '{{ item.name }}'
        state: absent
        remove: yes

    - name: Delete group
      become: yes
      loop: '{{ nodes }}'
      group:
        name: '{{ item.name }}'
        state: absent

    - name: Delete SystemD config
      become: yes
      loop: '{{ nodes }}'
      file:
        path: /etc/systemd/system/rococo-{{ item.name }}.service
        state: absent

    - name: Reload SystemD
      become: yes
      systemd:
        daemon_reload: yes

    - name: Delete Polkadot executable
      become: yes
      file:
        path: /usr/local/bin/polkadot
        state: absent
