---
- name: Configure WSS
  hosts: all
  vars:
    - email: hello@gear-tech.io

  tasks:
    - name: Install epel repository
      become: yes
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: latest
        update_cache: yes

    - name: Install Nginx, Certbot et al.
      become: yes
      yum:
        name: [nginx, certbot, python-certbot-nginx]
        state: latest
        update_cache: yes

    - name: Start Nginx
      become: yes
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create WWW directory
      become: yes
      file:
        path: /var/www/{{ inventory_hostname }}/html
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy index.html
      become: yes
      copy:
        remote_src: yes
        src: /usr/share/nginx/html/index.html
        dest: /var/www/{{ inventory_hostname }}/html/index.html

    - name: Copy Nginx configuration
      become: yes
      template:
        src: wss-server-block.j2
        dest: /etc/nginx/conf.d/{{ inventory_hostname }}.conf

    - name: Reload Nginx
      become: yes
      service:
        name: nginx
        state: reloaded

    - name: Install a certificate
      become: yes
      command: >
        certbot --nginx
        -d {{ inventory_hostname }}
        -m {{ email }}
        --agree-tos --noninteractive --redirect

    - name: Reload Nginx again
      become: yes
      service:
        name: nginx
        state: reloaded

    - name: Set cron job for auto renewal
      become: yes
      cron:
        name: Renew letsencrypt
        special_time: monthly
        job: /usr/bin/certbot renew
