---
- name: Backup DB
  hosts: all

  vars:
    nodes:
      - user: alice
        title: Default DB
        file_name: db
      - user: bob
        title: Archive DB
        file_name: db-archive

  tasks:
    - name: Stop service
      become: yes
      loop: '{{ nodes }}'
      systemd:
        name: vara-{{ item.user }}
        state: stopped

    - name: Generate checksum
      become: yes
      loop: '{{ nodes }}'
      shell:
        chdir: /home/{{ item.user }}/.local/share/gear-node/chains/vara_network/db
        cmd: 'find full -type f -exec md5sum {} \; > md5.txt'

    - name: Pack DB
      become: yes
      loop: '{{ nodes }}'
      archive:
        path: /home/{{ item.user }}/.local/share/gear-node/chains/vara_network/db
        dest: /var/www/{{ inventory_hostname }}/html/{{ item.file_name }}.tar.xz
        format: xz
        force_archive: yes

    - name: Get block number
      become: yes
      loop: '{{ nodes }}'
      become_user: '{{ item.user }}'
      register: block_number
      shell:
        cmd: /usr/local/bin/gear chain-info

    - name: Get stats of DB file
      become: yes
      loop: '{{ nodes }}'
      register: db_stats
      stat:
        path: /var/www/{{ inventory_hostname }}/html/{{ item.file_name }}.tar.xz

    - name: Update index.html
      become: yes
      template:
        src: snapshots-index.html.j2
        dest: /var/www/{{ inventory_hostname }}/html/index.html

    - name: Start service
      become: yes
      loop: '{{ nodes }}'
      systemd:
        name: vara-{{ item.user }}
        state: started
        enabled: yes
