---
- name: Install Vara Validator
  hosts: all
  vars_prompt:
    - name: node_name
      prompt: Node name
      private: no
    - name: seed_phrase
      prompt: Seed phrase
      private: no
  vars:
    executable: gear
    item:
      user: vara
      port_http: 9933
      port_ws: 9944
      port_p2p: 30333
      telemetry: wss://telemetry.rs
      validator: yes

  tasks:
    - name: Count words in seed phrase
      register: word_count
      command:
        argv:
          - wc
          - -w
        stdin: '{{ seed_phrase }}'

    - name: Validate 12-word seed phrase
      command:
        argv:
          - '['
          - '{{ word_count.stdout }}'
          - -eq
          - 12
          - ']'

    - name: Create group
      become: yes
      group:
        name: '{{ item.user }}'
        state: present

    - name: Create user
      become: yes
      user:
        name: '{{ item.user }}'
        groups: '{{ item.user }}'
        shell: /sbin/nologin
        append: yes
        state: present

    - name: Add user to sudo group
      become: yes
      shell: usermod -aG root {{ item.user }}

    - name: Download template
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/gear-tech/builds/master/ansible/vara/vara-node.service.j2
        dest: /tmp/vara-node.service.j2
        force: yes

    - name: Fetch template
      become: yes
      fetch:
        src: /tmp/vara-node.service.j2
        dest: ./
        flat: yes

    - name: Remove template file
      become: yes
      file:
        path: /tmp/vara-node.service.j2
        state: absent

    - name: Copy SystemD config
      become: yes
      template:
        src: vara-node.service.j2
        dest: /etc/systemd/system/vara-node.service
        owner: root
        group: root

    - name: Download and unpack Gear node executable
      become: yes
      unarchive:
        src: https://get.gear.rs/vara-nightly-linux-x86_64.tar.xz
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        owner: root
        group: root

    - name: Stop service
      become: yes
      systemd:
        name: vara-node
        state: stopped
        daemon_reload: yes

    - name: Add Babe key to the keystore
      become: yes
      become_user: '{{ item.user }}'
      command:
        argv:
          - /usr/local/bin/gear
          - key
          - insert
          - --key-type
          - babe
          - --scheme
          - sr25519
          - --suri
          - '{{ seed_phrase }}'

    - name: Add Grandpa key to the keystore
      become: yes
      become_user: '{{ item.user }}'
      command:
        argv:
          - /usr/local/bin/gear
          - key
          - insert
          - --key-type
          - gran
          - --scheme
          - ed25519
          - --suri
          - '{{ seed_phrase }}'

    - name: Start service
      become: yes
      systemd:
        name: vara-node
        state: started
        enabled: yes

    - name: Gathering service facts
      service_facts:
      tags: vara-node

    - name: Write vara-node status
      debug:
        var: ansible_facts.services["vara-node.service"]
