---
- name: Install Backup Vara Nodes
  hosts: all
  vars:
    executable: gear
    nodes:
      - user: alice
        node_name: vara-backup
        port_http: 9933
        port_ws: 9944
        port_p2p: 30333
        telemetry: wss://telemetry.rs

      - user: bob
        node_name: vara-backup-archive
        archive: yes
        port_http: 9934
        port_ws: 9945
        port_p2p: 30334
        telemetry: wss://telemetry.rs

  tasks:
    - name: Create group
      become: yes
      loop: '{{ nodes }}'
      group:
        name: '{{ item.user }}'
        state: present

    - name: Create user
      become: yes
      loop: '{{ nodes }}'
      user:
        name: '{{ item.user }}'
        groups: '{{ item.user }}'
        shell: /sbin/nologin
        append: yes
        state: present

    - name: Copy SystemD config
      become: yes
      loop: '{{ nodes }}'
      template:
        src: ../gear-node/gear-node.service.j2
        dest: /etc/systemd/system/vara-{{ item.user }}.service
        owner: root
        group: root

    - name: Stop service
      become: yes
      loop: '{{ nodes }}'
      systemd:
        name: vara-{{ item.user }}
        state: stopped
        daemon_reload: yes

    - name: Download and unpack Gear node executable
      become: yes
      unarchive:
        src: https://get.gear.rs/vara-nightly-linux-x86_64.tar.xz
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        owner: root
        group: root

    - name: Start service
      become: yes
      loop: '{{ nodes }}'
      systemd:
        name: vara-{{ item.user }}
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Stop logging
      become: yes
      register: rsyslog
      systemd:
        name: rsyslog
        state: stopped
        enabled: no

    - name: Reboot
      when: rsyslog is changed
      become: yes
      reboot:
