---
- name: Purge Vara Node's DB
  hosts: all
  vars:
    item:
      user: vara

  tasks:
    - name: Stop service
      become: yes
      systemd:
        name: vara-node
        state: stopped

    - name: Purge chain DB
      become_user: '{{ item.user }}'
      command: /usr/local/bin/gear purge-chain -y

    - name: Start service
      become: yes
      systemd:
        name: vara-node
        state: started
        enabled: yes

    - name: Gathering service facts
      service_facts:
      tags: vara-node

    - name: Write vara-node status
      debug:
        var: ansible_facts.services["vara-node.service"]
