---
- name: Remove Vara Node
  hosts: all
  vars:
    nodes:
      - user: vara

  tasks:
    - name: Stop service
      become: yes
      loop: '{{ nodes }}'
      ignore_errors: yes
      systemd:
        name: vara-node
        state: stopped

    - name: Delete user
      become: yes
      loop: '{{ nodes }}'
      user:
        name: '{{ item.user }}'
        state: absent
        remove: yes

    - name: Delete group
      become: yes
      loop: '{{ nodes }}'
      group:
        name: '{{ item.user }}'
        state: absent

    - name: Delete SystemD config
      become: yes
      loop: '{{ nodes }}'
      file:
        path: /etc/systemd/system/vara-node.service
        state: absent

    - name: Reload SystemD
      become: yes
      systemd:
        daemon_reload: yes

    - name: Delete Gear node executable
      become: yes
      file:
        path: /usr/local/bin/gear
        state: absent

    - name: Reboot
      become: yes
      reboot:
