name: Build for Amazon Linux

on:
  pull_request: # FIXME: Add to Nightly
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: amazonlinux:latest
    steps:
      - name: Install dependencies
        run: |
          yum install -y gcc git gzip make tar wget

      - name: Install CMake
        run: |
          wget https://cmake.org/files/v3.24/cmake-3.24.0-linux-x86_64.tar.gz
          tar -xvf cmake-3.24.0-linux-x86_64.tar.gz -O /usr/local
          rm cmake-3.24.0-linux-x86_64.tar.gz
          cmake --version

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gear-tech/gear

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Setup nightly WASM toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p gear-node --profile production
