name: Polkadot

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push node for workshop
        uses: docker/build-push-action@v2
        with:
          context: docker/polkadot
          push: true
          tags: |
            ghcr.io/gear-tech/polkadot:0.9.26
            ghcr.io/gear-tech/polkadot:latest
