name: Republish

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  republish:
    name: Republish artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create artifact directory
        run: mkdir -p artifact

      - name: Download old artifacts
        run: |
          cd artifact
          wget -nc https://get.gear.rs/gear-nightly-linux-x86_64.tar.xz && true
          wget -nc https://get.gear.rs/gear-nightly-linux-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-nightly-macos-m.tar.gz && true
          wget -nc https://get.gear.rs/gear-nightly-macos-m-version.txt && true
          wget -nc https://get.gear.rs/gear-nightly-macos-x86_64.tar.gz && true
          wget -nc https://get.gear.rs/gear-nightly-macos-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-nightly-windows-x86_64.zip && true
          wget -nc https://get.gear.rs/gear-nightly-windows-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.5-linux-x86_64.tar.xz && true
          wget -nc https://get.gear.rs/gear-v0.1.5-linux-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.5-macos-m.tar.gz && true
          wget -nc https://get.gear.rs/gear-v0.1.5-macos-m-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.5-macos-x86_64.tar.gz && true
          wget -nc https://get.gear.rs/gear-v0.1.5-macos-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.5-windows-x86_64.zip && true
          wget -nc https://get.gear.rs/gear-v0.1.5-windows-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.4-linux-x86_64.tar.xz && true
          wget -nc https://get.gear.rs/gear-v0.1.4-linux-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.4-macos-m.tar.gz && true
          wget -nc https://get.gear.rs/gear-v0.1.4-macos-m-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.4-macos-x86_64.tar.gz && true
          wget -nc https://get.gear.rs/gear-v0.1.4-macos-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.4-windows-x86_64.zip && true
          wget -nc https://get.gear.rs/gear-v0.1.4-windows-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.3-linux-x86_64.tar.xz && true
          wget -nc https://get.gear.rs/gear-v0.1.3-linux-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.3-macos-m.tar.gz && true
          wget -nc https://get.gear.rs/gear-v0.1.3-macos-m-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.3-macos-x86_64.tar.gz && true
          wget -nc https://get.gear.rs/gear-v0.1.3-macos-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.3-windows-x86_64.zip && true
          wget -nc https://get.gear.rs/gear-v0.1.3-windows-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.2-linux-x86_64.tar.xz && true
          wget -nc https://get.gear.rs/gear-v0.1.2-linux-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.2-macos-m.tar.gz && true
          wget -nc https://get.gear.rs/gear-v0.1.2-macos-m-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.2-macos-x86_64.tar.gz && true
          wget -nc https://get.gear.rs/gear-v0.1.2-macos-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.2-windows-x86_64.zip && true
          wget -nc https://get.gear.rs/gear-v0.1.2-windows-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.1-linux-x86_64.tar.xz && true
          wget -nc https://get.gear.rs/gear-v0.1.1-linux-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.1-macos-m.tar.gz && true
          wget -nc https://get.gear.rs/gear-v0.1.1-macos-m-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.1-macos-x86_64.tar.gz && true
          wget -nc https://get.gear.rs/gear-v0.1.1-macos-x86_64-version.txt && true
          wget -nc https://get.gear.rs/gear-v0.1.1-windows-x86_64.zip && true
          wget -nc https://get.gear.rs/gear-v0.1.1-windows-x86_64-version.txt && true
          wget -nc https://get.gear.rs/vara-testnet-linux-x86_64.tar.xz && true
          wget -nc https://get.gear.rs/vara-testnet-linux-x86_64-version.txt && true
          wget -nc https://get.gear.rs/vara-testnet-macos-m.tar.gz && true
          wget -nc https://get.gear.rs/vara-testnet-macos-m-version.txt && true
          wget -nc https://get.gear.rs/vara-testnet-macos-x86_64.tar.gz && true
          wget -nc https://get.gear.rs/vara-testnet-macos-x86_64-version.txt && true
          wget -nc https://get.gear.rs/vara-testnet-windows-x86_64.zip && true
          wget -nc https://get.gear.rs/vara-testnet-windows-x86_64-version.txt && true

      - name: Copy Ansible playbooks
        run: cp -rvf ansible artifact/

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Render index.html
        run: cargo run

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: artifact
          cname: get.gear.rs
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
