name: Republish

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  republish:
    name: Republish artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create artifact directory
        run: mkdir -p artifact

      - name: Download old artifacts
        run: |
          cd artifact
          wget -nc https://get.gear.rs/gear-nightly-x86_64-unknown-linux-gnu.tar.xz || true
          wget -nc https://get.gear.rs/gear-nightly-x86_64-unknown-linux-gnu-version.txt || true
          wget -nc https://get.gear.rs/gear-nightly-aarch64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-nightly-aarch64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-nightly-x86_64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-nightly-x86_64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-nightly-x86_64-pc-windows-msvc.zip || true
          wget -nc https://get.gear.rs/gear-nightly-x86_64-pc-windows-msvc-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.5-x86_64-unknown-linux-gnu.tar.xz || true
          wget -nc https://get.gear.rs/gear-v0.1.5-x86_64-unknown-linux-gnu-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.5-aarch64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-v0.1.5-aarch64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.5-x86_64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-v0.1.5-x86_64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.5-x86_64-pc-windows-msvc.zip || true
          wget -nc https://get.gear.rs/gear-v0.1.5-x86_64-pc-windows-msvc-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.4-x86_64-unknown-linux-gnu.tar.xz || true
          wget -nc https://get.gear.rs/gear-v0.1.4-x86_64-unknown-linux-gnu-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.4-aarch64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-v0.1.4-aarch64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.4-x86_64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-v0.1.4-x86_64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.4-x86_64-pc-windows-msvc.zip || true
          wget -nc https://get.gear.rs/gear-v0.1.4-x86_64-pc-windows-msvc-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.3-x86_64-unknown-linux-gnu.tar.xz || true
          wget -nc https://get.gear.rs/gear-v0.1.3-x86_64-unknown-linux-gnu-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.3-aarch64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-v0.1.3-aarch64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.3-x86_64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-v0.1.3-x86_64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.3-x86_64-pc-windows-msvc.zip || true
          wget -nc https://get.gear.rs/gear-v0.1.3-x86_64-pc-windows-msvc-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.2-x86_64-unknown-linux-gnu.tar.xz || true
          wget -nc https://get.gear.rs/gear-v0.1.2-x86_64-unknown-linux-gnu-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.2-aarch64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-v0.1.2-aarch64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.2-x86_64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-v0.1.2-x86_64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.2-x86_64-pc-windows-msvc.zip || true
          wget -nc https://get.gear.rs/gear-v0.1.2-x86_64-pc-windows-msvc-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.1-x86_64-unknown-linux-gnu.tar.xz || true
          wget -nc https://get.gear.rs/gear-v0.1.1-x86_64-unknown-linux-gnu-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.1-aarch64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-v0.1.1-aarch64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.1-x86_64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/gear-v0.1.1-x86_64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/gear-v0.1.1-x86_64-pc-windows-msvc.zip || true
          wget -nc https://get.gear.rs/gear-v0.1.1-x86_64-pc-windows-msvc-version.txt || true
          wget -nc https://get.gear.rs/vara-testnet-x86_64-unknown-linux-gnu.tar.xz || true
          wget -nc https://get.gear.rs/vara-testnet-x86_64-unknown-linux-gnu-version.txt || true
          wget -nc https://get.gear.rs/vara-testnet-aarch64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/vara-testnet-aarch64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/vara-testnet-x86_64-apple-darwin.tar.gz || true
          wget -nc https://get.gear.rs/vara-testnet-x86_64-apple-darwin-version.txt || true
          wget -nc https://get.gear.rs/vara-testnet-x86_64-pc-windows-msvc.zip || true
          wget -nc https://get.gear.rs/vara-testnet-x86_64-pc-windows-msvc-version.txt || true
          # Support legacy packages for backward compatibility
          cp -v gear-nightly-x86_64-unknown-linux-gnu.tar.xz gear-nightly-linux-x86_64.tar.xz || true
          cp -v gear-nightly-aarch64-apple-darwin.tar.gz gear-nightly-macos-m.tar.gz || true
          cp -v gear-nightly-x86_64-apple-darwin.tar.gz gear-nightly-macos-x86_64.tar.gz || true
          cp -v gear-nightly-x86_64-pc-windows-msvc.zip gear-nightly-windows-x86_64.zip || true
          cp -v vara-testnet-x86_64-unknown-linux-gnu.tar.xz vara-testnet-linux-x86_64.tar.xz || true
          cp -v vara-testnet-aarch64-apple-darwin.tar.gz vara-testnet-macos-m.tar.gz || true
          cp -v vara-testnet-x86_64-apple-darwin.tar.gz vara-testnet-macos-x86_64.tar.gz || true
          cp -v vara-testnet-x86_64-pc-windows-msvc.zip vara-testnet-windows-x86_64.zip || true

      - name: Copy Ansible playbooks
        run: cp -rvf ansible artifact/

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Render index.html
        run: cargo run

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: artifact
          cname: get.gear.rs
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
