name: Republish

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  republish:
    name: Republish artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create artifact directory
        run: mkdir -p artifact

      - name: Copy Ansible playbooks
        run: cp -rvf ansible artifact/

      - name: Download install script
        run: cd artifact && wget https://github.com/gear-tech/gear/raw/master/scripts/install.sh

      - name: Deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ansible/builds
          playbook: upload.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: -u ubuntu
          inventory: get.gear.rs
